# Generated by Django 6.0.5 on 2026-06-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpurchase',
            name='unit',
            field=models.CharField(help_text='e.g. kg, tons, liters', max_length=20),
        ),
    ]
